// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/my_account/my_project/myboolplanmodifier"
	"github.com/my_account/my_project/myboolvalidator"
)

var resourceResourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{
		"bool_attribute": schema.BoolAttribute{
			Computed: true,
			PlanModifiers: []planmodifier.Bool{
				boolplanmodifier.RequiresReplace(),
				myboolplanmodifier.Modify(),
			},
			Validators: []validator.Bool{
				myboolvalidator.Validate(),
			},
			Default: booldefault.StaticBool(true),
		},
	},
}
