// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func ExampleProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type ExampleModel struct {
}
