// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

var providerProviderSchema = schema.Schema{}

type ProviderModel struct {
}
