// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_petstore

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func PetstoreProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type PetstoreModel struct {
}
