// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"github.com/"
	"github.com/.../myplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
)

var exampleResourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{
		"bool_attribute": schema.BoolAttribute{
			CustomType: my_type,
			Computed:   true,
			PlanModifiers: []planmodifier.Bool{
				myplanmodifier.Modify(),
			},
			Default: booldefault.StaticBool(true),
		},
	},
}
