// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UserResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"first_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"last_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"password": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"phone": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"user_status": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "User Status",
				MarkdownDescription: "User Status",
			},
		},
	}
}

type UserModel struct {
	Email      types.String `tfsdk:"email"`
	FirstName  types.String `tfsdk:"first_name"`
	Id         types.Int64  `tfsdk:"id"`
	LastName   types.String `tfsdk:"last_name"`
	Password   types.String `tfsdk:"password"`
	Phone      types.String `tfsdk:"phone"`
	UserStatus types.Int64  `tfsdk:"user_status"`
}
