// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

var exampleProviderSchema = schema.Schema{}
