provider:
  name: apigw
  endpoint: "https://apigateway.apigw.ntruss.com/api/v1"
resources:
  product:
    dto_name: PostProductResponse
    # 고유 식별자이자 추후 다른 요청에서 사용하게 되는 id를 응답의 어디에서 가져올 수 있는지 알려줌.
    id: product.product_id
    create:
      path: /products
      method: POST
    read:
      path: /products/{product-id}
      method: GET
    update:
      - path: /products/{product-id}
        method: PATCH
    delete:
      path: /products/{product-id}
      method: DELETE
    schema:
      attributes:
        overrides:
          product.action_name:
            description: action name
          computed_optional_required: optional
          disabled:
            description: disabled
            computed_optional_required: optional
          permission:
            description: permission
            computed_optional_required: optional
          product_description:
            description: product description
            computed_optional_required: optional
          zone_code:
            description: zone code
            computed_optional_required: optional
data_sources:
  api_key:
    dto_name: ApiKeyDto
    read:
      path: /api-keys/{api-key-id}
      method: GET
      endpoint: PostApiKeys
