// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var datasourceDataSourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{
		"bool_attribute": schema.BoolAttribute{
			Computed: true,
		},
		"list_list_attribute": schema.ListAttribute{
			ElementType: types.ListType{
				ElemType: types.StringType,
			},
			Computed: true,
		},
		"list_map_attribute": schema.ListAttribute{
			ElementType: types.MapType{
				ElemType: types.StringType,
			},
			Computed: true,
		},
		"list_nested_attribute_one": schema.ListNestedAttribute{
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"bool_attribute": schema.BoolAttribute{
						Computed: true,
					},
				},
			},
			Computed: true,
		},
		"list_nested_attribute_three": schema.ListNestedAttribute{
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"list_nested_attribute_three_list_nested_attribute_one": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"list_attribute": schema.ListAttribute{
									ElementType: types.StringType,
									Computed:    true,
								},
							},
						},
						Computed: true,
					},
				},
			},
			Computed: true,
		},
		"list_nested_attribute_two": schema.ListNestedAttribute{
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"list_nested_attribute_two_list_nested_attribute_one": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"bool_attribute": schema.BoolAttribute{
									Computed: true,
								},
							},
						},
						Computed: true,
					},
				},
			},
			Computed: true,
		},
		"list_object_attribute": schema.ListAttribute{
			ElementType: types.ObjectType{
				AttrTypes: map[string]attr.Type{
					"obj_string_attr": types.StringType,
				},
			},
			Computed: true,
		},
		"list_object_object_attribute": schema.ListAttribute{
			ElementType: types.ObjectType{
				AttrTypes: map[string]attr.Type{
					"obj_obj_attr": types.ObjectType{
						AttrTypes: map[string]attr.Type{
							"obj_obj_string_attr": types.StringType,
						},
					},
				},
			},
			Computed: true,
		},
		"object_attribute": schema.ObjectAttribute{
			AttributeTypes: map[string]attr.Type{
				"obj_string_attr": types.StringType,
			},
			Computed: true,
		},
		"object_list_attribute": schema.ObjectAttribute{
			AttributeTypes: map[string]attr.Type{
				"obj_list_attr": types.ListType{
					ElemType: types.StringType,
				},
			},
			Computed: true,
		},
		"object_list_object_attribute": schema.ObjectAttribute{
			AttributeTypes: map[string]attr.Type{
				"obj_list_attr": types.ListType{
					ElemType: types.ObjectType{
						AttrTypes: map[string]attr.Type{
							"obj_list_obj_attr": types.StringType,
						},
					},
				},
			},
			Computed: true,
		},
		"single_nested_attribute_one": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"bool_attribute": schema.BoolAttribute{
					Computed: true,
				},
			},
			Computed: true,
		},
		"single_nested_attribute_three": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"single_nested_attribute_three_single_nested_attribute_one": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"list_attribute": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
					},
					Computed: true,
				},
			},
			Computed: true,
		},
		"single_nested_attribute_two": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"single_nested_attribute_two_single_nested_attribute_one": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"bool_attribute": schema.BoolAttribute{
							Computed: true,
						},
					},
					Computed: true,
				},
			},
			Computed: true,
		},
	},
	Blocks: map[string]schema.Block{
		"list_nested_block_one": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: map[string]schema.Attribute{
					"bool_attribute": schema.BoolAttribute{
						Computed: true,
					},
				},
			},
		},
		"list_nested_block_three": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Attributes: map[string]schema.Attribute{
					"object_attribute": schema.ObjectAttribute{
						AttributeTypes: map[string]attr.Type{
							"string_attribute_type": types.StringType,
						},
						Computed: true,
					},
				},
				Blocks: map[string]schema.Block{
					"list_nested_block_three_list_nested_block_one": schema.ListNestedBlock{
						NestedObject: schema.NestedBlockObject{
							Attributes: map[string]schema.Attribute{
								"list_attribute": schema.ListAttribute{
									ElementType: types.StringType,
									Computed:    true,
								},
							},
						},
					},
				},
			},
		},
		"list_nested_block_two": schema.ListNestedBlock{
			NestedObject: schema.NestedBlockObject{
				Blocks: map[string]schema.Block{
					"list_nested_block_two_list_nested_block_one": schema.ListNestedBlock{
						NestedObject: schema.NestedBlockObject{
							Attributes: map[string]schema.Attribute{
								"bool_attribute": schema.BoolAttribute{
									Computed: true,
								},
							},
						},
					},
				},
			},
		},
		"single_nested_block_one": schema.SingleNestedBlock{
			Attributes: map[string]schema.Attribute{
				"bool_attribute": schema.BoolAttribute{
					Computed: true,
				},
			},
		},
		"single_nested_block_three": schema.SingleNestedBlock{
			Attributes: map[string]schema.Attribute{
				"object_attribute": schema.ObjectAttribute{
					AttributeTypes: map[string]attr.Type{
						"string_attribute_type": types.StringType,
					},
					Computed: true,
				},
			},
			Blocks: map[string]schema.Block{
				"single_nested_block_three_list_nested_block_one": schema.ListNestedBlock{
					NestedObject: schema.NestedBlockObject{
						Attributes: map[string]schema.Attribute{
							"list_attribute": schema.ListAttribute{
								ElementType: types.StringType,
								Computed:    true,
							},
						},
					},
				},
			},
		},
		"single_nested_block_two": schema.SingleNestedBlock{
			Blocks: map[string]schema.Block{
				"single_nested_block_two_single_nested_block_one": schema.SingleNestedBlock{
					Attributes: map[string]schema.Attribute{
						"bool_attribute": schema.BoolAttribute{
							Computed: true,
						},
					},
				},
			},
		},
	},
}

type DatasourceModel struct {
	BoolAttribute              types.Bool   `tfsdk:"bool_attribute"`
	ListListAttribute          types.List   `tfsdk:"list_list_attribute"`
	ListMapAttribute           types.List   `tfsdk:"list_map_attribute"`
	ListNestedAttributeOne     types.List   `tfsdk:"list_nested_attribute_one"`
	ListNestedAttributeThree   types.List   `tfsdk:"list_nested_attribute_three"`
	ListNestedAttributeTwo     types.List   `tfsdk:"list_nested_attribute_two"`
	ListObjectAttribute        types.List   `tfsdk:"list_object_attribute"`
	ListObjectObjectAttribute  types.List   `tfsdk:"list_object_object_attribute"`
	ObjectAttribute            types.Object `tfsdk:"object_attribute"`
	ObjectListAttribute        types.Object `tfsdk:"object_list_attribute"`
	ObjectListObjectAttribute  types.Object `tfsdk:"object_list_object_attribute"`
	SingleNestedAttributeOne   types.Object `tfsdk:"single_nested_attribute_one"`
	SingleNestedAttributeThree types.Object `tfsdk:"single_nested_attribute_three"`
	SingleNestedAttributeTwo   types.Object `tfsdk:"single_nested_attribute_two"`
	ListNestedBlockOne         types.List   `tfsdk:"list_nested_block_one"`
	ListNestedBlockThree       types.List   `tfsdk:"list_nested_block_three"`
	ListNestedBlockTwo         types.List   `tfsdk:"list_nested_block_two"`
	SingleNestedBlockOne       types.Object `tfsdk:"single_nested_block_one"`
	SingleNestedBlockThree     types.Object `tfsdk:"single_nested_block_three"`
	SingleNestedBlockTwo       types.Object `tfsdk:"single_nested_block_two"`
}

type ListNestedAttributeOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type ListNestedAttributeThreeModel struct {
	ListNestedAttributeThreeListNestedAttributeOne types.List `tfsdk:"list_nested_attribute_three_list_nested_attribute_one"`
}

type ListNestedAttributeThreeListNestedAttributeOneModel struct {
	ListAttribute types.List `tfsdk:"list_attribute"`
}

type ListNestedAttributeTwoModel struct {
	ListNestedAttributeTwoListNestedAttributeOne types.List `tfsdk:"list_nested_attribute_two_list_nested_attribute_one"`
}

type ListNestedAttributeTwoListNestedAttributeOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type SingleNestedAttributeOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type SingleNestedAttributeThreeModel struct {
	SingleNestedAttributeThreeSingleNestedAttributeOne types.Object `tfsdk:"single_nested_attribute_three_single_nested_attribute_one"`
}

type SingleNestedAttributeThreeSingleNestedAttributeOneModel struct {
	ListAttribute types.List `tfsdk:"list_attribute"`
}

type SingleNestedAttributeTwoModel struct {
	SingleNestedAttributeTwoSingleNestedAttributeOne types.Object `tfsdk:"single_nested_attribute_two_single_nested_attribute_one"`
}

type SingleNestedAttributeTwoSingleNestedAttributeOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type ListNestedBlockOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type ListNestedBlockThreeModel struct {
	ObjectAttribute                        types.Object `tfsdk:"object_attribute"`
	ListNestedBlockThreeListNestedBlockOne types.List   `tfsdk:"list_nested_block_three_list_nested_block_one"`
}

type ListNestedBlockThreeListNestedBlockOneModel struct {
	ListAttribute types.List `tfsdk:"list_attribute"`
}

type ListNestedBlockTwoModel struct {
	ListNestedBlockTwoListNestedBlockOne types.List `tfsdk:"list_nested_block_two_list_nested_block_one"`
}

type ListNestedBlockTwoListNestedBlockOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type SingleNestedBlockOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

type SingleNestedBlockThreeModel struct {
	ObjectAttribute                          types.Object `tfsdk:"object_attribute"`
	SingleNestedBlockThreeListNestedBlockOne types.List   `tfsdk:"single_nested_block_three_list_nested_block_one"`
}

type SingleNestedBlockThreeListNestedBlockOneModel struct {
	ListAttribute types.List `tfsdk:"list_attribute"`
}

type SingleNestedBlockTwoModel struct {
	SingleNestedBlockTwoSingleNestedBlockOne types.Object `tfsdk:"single_nested_block_two_single_nested_block_one"`
}

type SingleNestedBlockTwoSingleNestedBlockOneModel struct {
	BoolAttribute types.Bool `tfsdk:"bool_attribute"`
}

func (m ListNestedAttributeThreeModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedAttributeThreeModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_nested_attribute_three_list_nested_attribute_one": types.ListType{
			ElemType: ListNestedAttributeThreeListNestedAttributeOneModel{}.ObjectType(),
		},
	}
}

func (m ListNestedAttributeThreeListNestedAttributeOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedAttributeThreeListNestedAttributeOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_attribute": types.ListType{
			ElemType: types.StringType,
		},
	}
}
func (m ListNestedAttributeTwoModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedAttributeTwoModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_nested_attribute_two_list_nested_attribute_one": types.ListType{
			ElemType: ListNestedAttributeTwoListNestedAttributeOneModel{}.ObjectType(),
		},
	}
}

func (m ListNestedAttributeTwoListNestedAttributeOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedAttributeTwoListNestedAttributeOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bool_attribute": types.BoolType,
	}
}
func (m SingleNestedAttributeThreeModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedAttributeThreeModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"single_nested_attribute_three_single_nested_attribute_one": types.ObjectType{
			AttrTypes: SingleNestedAttributeThreeSingleNestedAttributeOneModel{}.ObjectAttributeTypes(),
		},
	}
}

func (m SingleNestedAttributeThreeSingleNestedAttributeOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedAttributeThreeSingleNestedAttributeOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_attribute": types.ListType{
			ElemType: types.StringType,
		},
	}
}
func (m SingleNestedAttributeTwoModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedAttributeTwoModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"single_nested_attribute_two_single_nested_attribute_one": types.ObjectType{
			AttrTypes: SingleNestedAttributeTwoSingleNestedAttributeOneModel{}.ObjectAttributeTypes(),
		},
	}
}

func (m SingleNestedAttributeTwoSingleNestedAttributeOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedAttributeTwoSingleNestedAttributeOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bool_attribute": types.BoolType,
	}
}
func (m ListNestedBlockThreeModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedBlockThreeModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_nested_block_three_list_nested_block_one": types.ListType{
			ElemType: ListNestedBlockThreeListNestedBlockOneModel{}.ObjectType(),
		},
		"object_attribute": types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"string_attribute_type": types.StringType,
			},
		},
	}
}

func (m ListNestedBlockThreeListNestedBlockOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedBlockThreeListNestedBlockOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_attribute": types.ListType{
			ElemType: types.StringType,
		},
	}
}
func (m ListNestedBlockTwoModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedBlockTwoModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_nested_block_two_list_nested_block_one": types.ListType{
			ElemType: ListNestedBlockTwoListNestedBlockOneModel{}.ObjectType(),
		},
	}
}

func (m ListNestedBlockTwoListNestedBlockOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m ListNestedBlockTwoListNestedBlockOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bool_attribute": types.BoolType,
	}
}
func (m SingleNestedBlockThreeModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedBlockThreeModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"object_attribute": types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"string_attribute_type": types.StringType,
			},
		},
		"single_nested_block_three_list_nested_block_one": types.ListType{
			ElemType: SingleNestedBlockThreeListNestedBlockOneModel{}.ObjectType(),
		},
	}
}

func (m SingleNestedBlockThreeListNestedBlockOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedBlockThreeListNestedBlockOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"list_attribute": types.ListType{
			ElemType: types.StringType,
		},
	}
}
func (m SingleNestedBlockTwoModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedBlockTwoModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"single_nested_block_two_single_nested_block_one": types.ObjectType{
			AttrTypes: SingleNestedBlockTwoSingleNestedBlockOneModel{}.ObjectAttributeTypes(),
		},
	}
}

func (m SingleNestedBlockTwoSingleNestedBlockOneModel) ObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: m.ObjectAttributeTypes()}
}

func (m SingleNestedBlockTwoSingleNestedBlockOneModel) ObjectAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bool_attribute": types.BoolType,
	}
}
