# Continuous integration handling for Go
name: ci-go

on:
  pull_request:
    paths:
      - .github/workflows/ci-go.yml
      - .golangci.yml
      - go.mod
      - '**.go'

permissions:
  contents: read

env:
  GOPRIVATE: github.com/hashicorp/terraform-plugin-codegen-spec

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
      - run: git config --global url.https://${{ secrets.TF_DEVEX_COMMIT_GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/
      - run: go mod download
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
      - run: git config --global url.https://${{ secrets.TF_DEVEX_COMMIT_GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/
      - run: go mod download
      - run: go test -coverprofile=coverage.out ./...
      - run: go tool cover -html=coverage.out -o coverage.html
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: go-coverage
          path: coverage.html